const USE_AFTER_AOP = 'USE_AFTER_AOP'
const USE_BEFORE_AOP ='USE_BEFORE_AOP'
const AFTER_AOP = 'AFTER_AOP'
const BEFORE_AOP = 'BEFORE_AOP'

const PARAMS_INDEX = 'paramsIndex'
const PARAMS = 'params'

export {USE_BEFORE_AOP,USE_AFTER_AOP,AFTER_AOP,BEFORE_AOP,PARAMS_INDEX,PARAMS}

